[package]
name = "krnl-rs"
version = "0.1.0"
edition = "2021"

# [dependencies.core]
# version = "1.39"
# features = ["fmt", "string",]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort" # No backtrace for panics

[profile.release]
panic = "abort" # No backtrace for panics
