[package]
name = "krnl-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = { version = "0.9", features = ["x86_64"] }
x86_64 = "0.15.1"

[profile.dev]
panic = "abort" # No backtrace for panics

[profile.release]
panic = "abort" # No backtrace for panics
